# Setup
title:               Jiwon
description:         'Development Blog'
url:                 https://lgm0905.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jiwon Lee
  url:               ''
  email:             lgm0905@snu.ac.kr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
